### ISSUE TITLE
We seem to be suddenly getting this issue. We haven't changed our logic, and maybe we rarely got this before, but now it is happening a lot more. We should look into the why.

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/label-bot#106]
```
Jul 22 19:31:55 gir-label-bot app/web.1 Traceback (most recent call last):
Jul 22 19:31:55 gir-label-bot app/web.1   File "/app/label_bot/__main__.py", line 35, in deferred_commands
Jul 22 19:31:55 gir-label-bot app/web.1     async for cmd in commands.run(event, gh, bot):
Jul 22 19:31:55 gir-label-bot app/web.1   File "/app/label_bot/commands.py", line 171, in run
Jul 22 19:31:55 gir-label-bot app/web.1     comment = await gh.getitem(event.data[etype]['url'], accept=util.HTML_HEADER)
Jul 22 19:31:55 gir-label-bot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/abc.py", line 126, in getitem
Jul 22 19:31:55 gir-label-bot app/web.1     "GET", url, url_vars, b"", accept, jwt=jwt, oauth_token=oauth_token
Jul 22 19:31:55 gir-label-bot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/abc.py", line 106, in _make_request
Jul 22 19:31:55 gir-label-bot app/web.1     data, self.rate_limit, more = sansio.decipher_response(*response)
Jul 22 19:31:55 gir-label-bot app/web.1   File "/app/.heroku/python/lib/python3.6/site-packages/gidgethub/sansio.py", line 366, in decipher_response
Jul 22 19:31:55 gir-label-bot app/web.1     raise exc_type(*args)
Jul 22 19:31:55 gir-label-bot app/web.1 gidgethub.BadRequest: Not Found
```

**Comment by facelessuser** [comment]
We addressed this with #107. Yet I haven't been able to replicate it since putting the retry in...go figure.  I think we'll just close this issue for now. If it surfaces again, or the workaround doesn't work like we expect, we can revisit this with a new issue.
